# Generated by Django 5.0.2 on 2024-03-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_recipe_created_on_alter_recipe_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='updated_on',
        ),
    ]
